tap "homebrew/bundle"
tap "homebrew/cask-fonts"
# tap "int128/kubelogin"
# brew "azure-cli"
brew "bandwhich"
brew "bat"
brew "bmon"
brew "btop"
brew "direnv"
brew "doctl"
brew "duf"
brew "eza"
brew "fx"
brew "fzf"
brew "glow"
brew "jq"
brew "just"
brew "lazydocker"
brew "lazygit"
brew "mas"
brew "monolith"
brew "neovim"
brew "node"
brew "pipx"
brew "postgresql@14"
brew "python@3.12"
brew "ripgrep"
brew "rust"
brew "starship"
brew "vapor"
brew "zellij"
# brew "int128/kubelogin/kubelogin"
cask "font-ubuntu-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-hack-nerd-font"
